### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by suroegin** [joepie91/python-whois#1]
Hello!
I've just installed this module and created simple file with:

import sys, pythonwhois
testlist = open("domains.txt").readlines()
raw, result = pythonwhois.whois(sys.argv[1])
print raw
print result

Python interpreter say me:

"IndexError: list index out of range" in the 3-th line.
How to fix it?

With regards, 
Ivan.

**Comment by joepie91** [comment]
Hi!

In your code, you're trying to read sys.argv - this is basically the list that holds all commandline parameters passed on to your script. Since you're trying to read from domains.txt and not passing on commandline parameters, that won't work. If you want to do a mass-lookup of all the domains in domains.txt, you'd be looking at something like this:

``` python
import pythonwhois

for line in open("domains.txt"):
    raw, result = pythonwhois.whois(line.strip())
    print raw
    print result
```

The `for line in open(...)` is a quick method to run code "for every line in a file". The strip() serves to remove the trailing newline for the line.

To elaborate a bit more on the error message you are getting: an IndexError occurs when you are trying to retrieve an element from a list that does not exist. If, for example, you had a list that holds 4 values, trying to retrieve the fifth (zero-based, so list[4]) would raise an IndexError because there is no fifth. Since the sys.argv list _always_ exists and holds the first argument - the script name - it will raise an IndexError when you're trying to retrieve a non-existent parameter.
- Sven

**Comment by suroegin** [comment]
Sven, thank you for good answer!
And.. Last problem, I'm sorry..

```
Traceback (most recent call last):
  File "whois.py", line 4, in <module>
    raw, result = pythonwhois.whois(line.strip())
  File "/usr/local/lib/python2.7/dist-packages/pythonwhois-1.2.2-py2.7.egg/pythonwhois/__init__.py", line 166, in whois
    ping = subprocess.Popen(["jwhois", encoded_domain], stdout = subprocess.PIPE, stderr = subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

With regards, 
Ivan.

**Comment by joepie91** [comment]
Ah, you most likely do not have `jwhois` installed (this is currently required to use python-whois).

If you're using Debian (or a derivative), `apt-get install jwhois` should do the job. On CentOS/Fedora/RedHat, `yum install jwhois` should work. Other distributions might have different package managers or package names - either way, look for whatever package contains the `jwhois` binary. Good luck!
- Sven

**Comment by suroegin** [comment]
Sven, thank you very much!
App is working very well!

With regards, 
Ivan.
