### ISSUE TITLE
Fail to print out WHOis data in my python application

### ISSUE THREAD

**Issue by mdagcilar** [joepie91/python-whois#104]
I'm trying to use the 'pythonwhois.get_whois(domain, True)' API in my python application.

Calling print on this line gives me the format of the data obviously just on one line. 

Like below: 
![untitled](https://cloud.githubusercontent.com/assets/6627550/11447678/3b8f2dbc-9542-11e5-8562-bd0c691b7484.png)

how can i get the output to be printed like the Command Line Tool?

Thanks

**Comment by joepie91** [comment]
The `get_whois` method just returns structured Python data (nested lists, dicts, strings, dates), so that you can use it in your application and store or format it as you wish. You should also be able to `json.dumps` it if necessary, using [this code](https://github.com/joepie91/python-whois/blob/master/pwhois#L16-L20) to encode the datetime objects.

The "pretty formatting" of WHOIS data is currently something that's only implemented in the `pwhois` tool itself, as it's unlikely to be useful for programmatic use. If you absolutely need such formatting in your application, you could always copy the relevant parts from the [`pwhois` source](https://github.com/joepie91/python-whois/blob/master/pwhois) :)

**Comment by mdagcilar** [comment]
Ah great, thanks!
