### ISSUE TITLE
example.com - No root WHOIS server found for TLD

### ISSUE THREAD

**Issue by obormot** [joepie91/python-whois#17]
v2.1.4

```
>>> pythonwhois.get_whois('example.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pythonwhois/__init__.py", line 4, in get_whois
    raw_data = net.get_whois_raw(domain)
  File "pythonwhois/net.py", line 24, in get_whois_raw
    target_server = get_root_server(domain)
  File "pythonwhois/net.py", line 60, in get_root_server
    raise shared.WhoisException("No root WHOIS server found for TLD.")
pythonwhois.shared.WhoisException: No root WHOIS server found for TLD.
```

**Comment by joepie91** [comment]
Fixed in 2.2.0. This was broken due to IANA not correctly returning a WHOIS server for `example.com`; presumably, this is a corner case. Run `pip install --upgrade pythonwhois` to update.

Keep in mind that this is a potentially breaking update, and if your application requires unmodified raw WHOIS data, you will need to pass an extra parameter to `get_whois_raw` (see the updated `README`). If your application uses parsed data only (or if modified raw data is okay), you will not need to make any changes.
