### ISSUE TITLE
another regex explosion

### ISSUE THREAD

**Issue by obormot** [joepie91/python-whois#18]
This is similar to issue #2. The call takes ~400s to complete; if interrupted, the traceback is somewhere is `re` module.

```
>>> import pythonwhois
>>> pythonwhois.get_whois('drpciv.biz')
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/lib/python2.7/site-packages/pythonwhois/__init__.py", line 5, in get_whois
    return parse.parse_raw_whois(raw_data, normalized=normalized)
  File "[...]/lib/python2.7/site-packages/pythonwhois/parse.py", line 255, in parse_raw_whois
    data["contacts"] = parse_registrants(raw_data)
  File "[...]/lib/python2.7/site-packages/pythonwhois/parse.py", line 639, in parse_registrants
    match = re.search(regex, segment)
  File "[...]/lib/python2.7/re.py", line 148, in search
    return _compile(pattern, flags).search(string)
KeyboardInterrupt
```

**Comment by joepie91** [comment]
Yup, I can reproduce the problem here. I'll have a look at it in a moment.

**Comment by joepie91** [comment]
Whoops, this is not actually closed yet. Accidentally committed my change on master. The hang is fixed now, but it doesn't parse .biz yet.

**Comment by joepie91** [comment]
Fixed in 2.2.1, which I just released. The domain you specified is now also correctly parsed - apparently State/Province fields are not reliably present for NeuStar (which handles .us and .biz).

You can upgrade using `pip install --upgrade pythonwhois` - if you're running on 2.1.x, please be aware that there's a small possibly breaking change in the 2.2 branch, if you require unmodified raw WHOIS responses. Details can be found [here](https://github.com/joepie91/python-whois#important-update-notes).

**Comment by obormot** [comment]
that was fast!

**Comment by joepie91** [comment]
I try to maintain projects well :)
