### ISSUE TITLE
All the country name are not in standard format

### ISSUE THREAD

**Issue by rajnish-garg** [joepie91/python-whois#33]
Hi,

I was retrieving the whois data for multiple ccTLD and gTLD and I found that some Countries name are in abbreviation and while some has full name. 

While parsing the data, can we parse those name into one standard format. In my script I have used following country code mapping data:

http://www.worldatlas.com/aatlas/ctycodes.htm

**Comment by joepie91** [comment]
Can you verify what version of pythonwhois you are running? This is how you can check:

``` bash
pip freeze | grep pythonwhois
```

The current version is `2.4.2`, but country name normalization was introduced in `2.4.0`. If you are using a version earlier than `2.4.0`, you should definitely update.

There has been a large performance improvement on Python 2.x since `2.4.0`, and in normalized mode it will convert country code abbreviations to full country names, as well as some other commonly abbreviated locality names (airport codes and US/CA/AU states).

If you are running `2.4.0` or higher and it still gives you country code abbreviations, then this is a bug, and it would be helpful if you could provide some examples of incorrectly parsed domains. Make sure that you have normalization turned on - in default mode, the conversion doesn't happen.

**Comment by rajnish-garg** [comment]
Thanks for clarifiying
