### ISSUE TITLE
Error while parsing some domains.

### ISSUE THREAD

**Issue by mariuskagc** [joepie91/python-whois#57]
I am having issues while parsing some domains:

```
whois_data = get_whois(domain)
```

  File "/usr/local/lib/python2.7/dist-packages/pythonwhois/**init**.py", line 4, in get_whois
    raw_data, server_list = net.get_whois_raw(domain, with_server_list=True)
  File "/usr/local/lib/python2.7/dist-packages/pythonwhois/net.py", line 69, in get_whois_raw
    return get_whois_raw(domain, referal_server, new_list, server_list=server_list, with_server_list=with_server_list)
  File "/usr/local/lib/python2.7/dist-packages/pythonwhois/net.py", line 44, in get_whois_raw
    response = whois_request(request_domain, target_server)
  File "/usr/local/lib/python2.7/dist-packages/pythonwhois/net.py", line 94, in whois_request
    return buff.decode("utf-8")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf3 in position 1345: invalid continuation byte

Looks like library is not parsing well. 
pythonwhois version:
pip search pythonwhois
pythonwhois - Module for retrieving and parsing the WHOIS data for a domain. Supports most domains. No dependencies.
INSTALLED: 2.4.3 (latest)

domain tested:
sesise.com
gcbcapp.com

Trying with linux whois you can see especial characters on some text or contacts, respectively.
Example for gcbapp.com:
$ whois gcbcapp.com
[...]
Technical Contact:
  technical_contact_organization: Uni▒ Empresaris Hostaleria i Turisme Costa Brava
  technical_contact_name: Teresa Marqu▒s
  technical_contact_address1: Ctra. Palam▒s, km. 328

**Comment by obskyr** [comment]
I'm also having this exact problem.

``` python
  File "C:\Python27\lib\site-packages\pythonwhois\net.py", line 95, in whois_request
    return buff.decode("utf-8")
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 590: invalid start byte
```

I've traced the error to a page served by http://whois.cronon.net/ - and I think I already see the problem. From the DTD of [the Cronon whois page](http://whois.cronon.net/cgi-bin/who.cgi):

``` html
<?xml version="1.0" encoding="iso-8859-1"?>
```

This means that Cronon uses the iso-8859-1 encoding instead of UTF-8, which is a bit of a pain. Pythonwhois simply doesn't account for any encodings other than UTF-8.

There are two ways to solve this, as far as I can see. Either we replace `buff.decode('utf-8')` with `buff.decode('utf-8', errors='ignore')` or `buff.decode('utf-8', errors='replace')`, but this will mean we lose some data, which obviously isn't really desirable.

The other solution would be to determine the encoding of the page before decoding it. This could be done by checking for encoding declarations in the DTD (as Cronos used) and / or check for `<meta charset="[blahblahblah]">` tags. I suppose you could also just wrap the decode in a try / except chain, but that'd mean pages in non-UTF-8 encodings but without incorrect characters would slip through, which isn't really nice.

Anyone want to weigh in on this?

**Comment by joncombe** [comment]
Same issue when looking at: rikke.fi

This is a fantastic project, thanks for your great work so far.

**Comment by joepie91** [comment]
I've created a new canonical thread for this in #97.
