### ISSUE TITLE
is the project abandoned?

### ISSUE THREAD

**Issue by obormot** [joepie91/python-whois#73]
I've seen this project booming early on but for the past 6+ months it looks quite a bit stranded. There are some stale pull requests. @joepie91 are you planning to continue developing and/or maintaining it?  Thanks

**Comment by joepie91** [comment]
Sorry for that! The project is definitely not abandoned, I've just been really busy putting out various other fires. My financial situation is fairly bad right now as well, so that doesn't really make things easier either.

I'll most likely do a batch run through all the outstanding issues and pull requests in a few days or so. I don't really have an exact date yet - right now I'm working on an infrastructure upgrade for [another project of mine](https://pdf.yt/) which takes a lot of time, but after that I should hopefully have time to take care of `python-whois`.

**Comment by obormot** [comment]
Thanks, it's encouraging to hear from the author! 
Hopefully folks who have started using python-whois in their projects will donate when such option becomes available.

**Comment by joepie91** [comment]
It is actually [already possible](http://cryto.net/~joepie91/donate.html), but I seem to have forgotten to add that to the documentation :)

**Comment by joepie91** [comment]
Changes are happening again! I had some issues with my environment, but @hangtwenty found the solution for those in #96.

I hope to release a new version soon, but the encoding issues need to be resolved first - if you can help with that, then there's an issue thread with all the relevant information at #97.
