### ISSUE TITLE
Do you need a new maintainer?

### ISSUE THREAD

**Issue by floer32** [joepie91/python-whois#96]
Noticing a lot of a open pull requests. Happy to join on maintenance, or to take over. Never done that before, so I'm not sure exactly the best process. This is a great library, I'd be happy to help. Let me know!

**Comment by joepie91** [comment]
Thanks for the offer :)

I could use some help, though I'm rather rigorous where it concerns code quality (eg. I've rejected or required modifications on PRs for typos and style issues before), so it'd depend on how high your review standards are. I'm not quite a BDFL, but some people do see me as such, because I don't budge on decisions without a good counter-rationale... and discussions can get pretty intense.

The reason for the large amount of open issues and PRs is two-fold:
1. Python has been most uncooperative, and I have yet to succeed at getting 2.6, 2.7 and 3.x to run simultaneously on my new system, as is required for the tests. `altinstall` is completely broken for me, and I can't figure out the reason for it.
2. I've had some financial issues recently, which led to not having much time for maintaining this library. Things are clearing up a bit now, though, so I should be able to work on it again soon... once I've gotten my development environment in proper working order.

I've been messing with [Nix](https://nixos.org/nix/) on my system lately - if I can get a working set of Python packages with that, I should probably be fine, and be able to run tests again. Either way, an extra pair of eyes probably wouldn't hurt, as long as you're comfortable with the above :)

**Comment by floer32** [comment]
Got it... I am sorry to hear about (2). I understand.

Re (1), I wonder if I can help. What OS and/or distro are you using? Have you tried [pyenv](https://github.com/yyuu/pyenv)?

**Comment by joepie91** [comment]
Thanks! After nuking the broken `altinstall`s from my system, `pyenv` solved the problem, and I can now run the Tox tests successfully again. The distro/version I'm using is openSUSE 13.1 x86_64, for what it's worth :)

I'll start getting to work on some issues tonight. Given what I've described about the project maintenance strategy, would you still be interested in being a co-maintainer?

**Comment by joepie91** [comment]
Also, in case you'd like to help out with python-whois in any (non-maintainer) way, there's now issue #97, which is a canonical issue thread for the ongoing encoding issues... frankly, they're doing my head in and I've completely lost track of how to reliably fix them across Python versions. If you could help figuring that out, it'd be very welcome!

**Comment by floer32** [comment]
@joepie91 So glad to hear that pyenv helped. I learned about pyenv from @hummus , a friend of mine who is also very appreciative of this lib and may contribute some things.

Just learned about [your donate button](http://cryto.net/~joepie91/donate.html) from #73, you should add the link to the README! ;)

Thanks again for your responsiveness. Regarding "becoming a co-maintainer" I'm not positive I'll live up to all standards ... I can start with some contributions. I'll check out #97, your round-up of related work will be very helpful. Cheers.

**Comment by joepie91** [comment]
That'd be much appreciated. We'll see how things turn out with contributions - if things work out well, I can always add you as a co-maintainer if you'd like a later point, of course.

I'll certainly be putting a donation link in the README for the next release :) There probably won't be a release until the encoding issues are fixed, though. Releasing a new version that's broken in a different way would just be causing needless headaches for users, as they have to figure things out again - at least now it's clear what works and what doesn't, and people can work around it to some degree, until a properly fixed version is completed.

**Comment by floer32** [comment]
:+1:

**Comment by floer32** [comment]
Hey not sure if this is helpful or not. BTW sorry I disappeared ... we were talking just before I got involved in the most intense work-based project of my career yet and I let everything get way out of balance :X maybe I will have more time now.

Just wanted to mention two things:
- No donate button in README yet?
- Also, if you are finding some of these issues are filed by commercial interests, I've recently learned about https://www.bountysource.com/ ... if you think it is relevant, maybe you could mention this in a README and nudge people to post a bounty if they want an issue fast-tracked. This came to mind because of [point 2 mentioned in this comment](https://github.com/joepie91/python-whois/issues/96#issuecomment-135924153)
